#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server: 
  port: 1112

#服务名称
spring:
  application:
    name: provider-1112
#  #服务链路跟踪到zipkin服务
#  zipkin:
#    base-url: http://localhost:1115
  ##  zipkin 链路跟踪配置
  sleuth:
    enabled: true
    #采样率，越高会有性能影响
    sampler:
      percentage: 1.0
  cloud:
    ## kafka zk配置 配合zipkin
    stream:
      kafka:
        binder:
          brokers: 192.168.206.203:9092
          zkNodes: 192.168.206.203:2181
  #springboot-admin 1.5.6集成使用
  boot:
    admin:
      auto-registration: true
      # springboot admin的地址
      url: http://localhost:8080
      api-path: instances
      client:
        prefer-ip: true
#不使用鉴权
management:
  security:
    enabled: false