#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server: 
  port: 1112

#服务名称
spring:
  application:
    name: provider-1112
  #服务链路跟踪到zipkin服务
  zipkin:
    base-url: http://localhost:1115